export const NATIVE_MENU_LABELS = {
  roleAbout: 'About {appName}',
  roleAboutGeneric: 'About',
  roleServices: 'Services',
  roleHide: 'Hide {appName}',
  roleHideOthers: 'Hide Others',
  roleUnhide: 'Show All',
  roleQuit: 'Quit {appName}',
  roleQuitGeneric: 'Quit',
  roleExit: 'Exit',
  roleUndo: 'Undo',
  roleRedo: 'Redo',
  roleCut: 'Cut',
  roleCopy: 'Copy',
  rolePaste: 'Paste',
  roleSelectAll: 'Select All',
  roleReload: 'Reload',
  roleForceReload: 'Force Reload',
  roleToggleDevTools: 'Toggle Developer Tools',
  roleResetZoom: 'Actual Size',
  roleZoomIn: 'Zoom In',
  roleZoomOut: 'Zoom Out',
  roleToggleFullScreen: 'Toggle Full Screen',
  roleMinimize: 'Minimize',
  roleZoom: 'Zoom',
  roleFront: 'Bring All to Front',
  roleCloseWindow: 'Close Window',
  roleClose: 'Close',

  menuFile: 'File',
  menuEdit: 'Edit',
  menuView: 'View',
  menuTerminal: 'Terminal',
  menuWindow: 'Window',
  menuHelp: 'Help',

  recentProject: 'Recent project',
  recentFiles: 'Recent files',
  noRecentProjects: 'No recent projects',
  noRecentFiles: 'No recent files',
  clearMenu: 'Clear menu',

  addToDictionary: 'Add to Dictionary',
  disableSpellCheck: 'Disable Spell Check',
  enableSpellCheck: 'Enable Spell Check',
  lookUpWord: 'Look Up "{word}"',
  searchWithGoogle: 'Search with Google',
  viewInSourceMarkdown: 'View in Source Markdown',

  showInExplorer: 'Show in Explorer',
  openInFileManager: 'Open in file manager',
  openInDefaultApp: 'Open in default app',
  copyLink: 'Copy link',
} as const satisfies Record<string, string>;

export type NativeMenuLabelKey = keyof typeof NATIVE_MENU_LABELS;
